### ISSUE TITLE
The command URDUHACK DOWNLOAD seems not working on windows

### ISSUE THREAD

**Issue by AatifMuhammad** [urduhack/urduhack#102]
Dear all, I am not a developer and using the github for the first time, too. I am working on a research problem. As usual I always google things to implement ideas and solve problems. Currently I am solving a research problem in Urdu language for which I need a library like NLTK. During browsing I encountered urduhack library. However, when I tried to use/test it I faced a problem. Everything seems to be working fine except the command **_urduhack download_**.  During testing an error message is thrown as shown in the error message below [
![Error message](https://user-images.githubusercontent.com/39222895/80962398-6c97a380-8e26-11ea-97fa-0798cfa571ae.png)
](url) 

The error message guides to execute the command **urduhack download** in the terminal. When executed the command as shown in the image below the error still exists. 
[
![running command at terminal 1](https://user-images.githubusercontent.com/39222895/80962667-e334a100-8e26-11ea-8950-1f66ad99419b.png)
](url)
From the above anaconda environment screenshot it seems like the command **urduhack download** does not executes at all because visually nothing happens on the screen as a result of the command e.g a success message, a failure message etc. Therefore, I think there is a problem with this command on windows. 

## How to reproduce the behaviour
urduhack download

## Your Environment
* Operating System: Windows 10 Education (64-bit)
* Python Version Used: 3.6
* Urduhack Version Used: 0.2.7
* Environment Information: I am using Spyder IDE version 4.1.1 on HP Laptop intel(R) Core(TM) i5-3230M CPU @ 2.60GHz 2.60 GHz with 4 GB RAM.

**Comment by AatifMuhammad** [comment]
Respected @akkefa et al help is required in this regard. Thank You

**Comment by akkefa** [comment]
@AatifMuhammad Did you try to use Urduhack on google colab?

**Comment by AatifMuhammad** [comment]
> @AatifMuhammad Did you try to use Urduhack on google colab?

No brother @akkefa . As I stated in the issue at the very beginning that I am not a developer therefore, you may find it very strange to know that 'I have heard the name _google colab_ for the first time'. However, I just gave a superficial view to the Home page of google colab and I think it will be a life changing point for me to use google colab becuase I think it provides an intelligent coding environment. 
Regarding Urduhack, as I had no choice but to leave Urduhack for the time being, therefore, I did that and googling for possible pieces of codes that could help me in solving my problem.

**Comment by AatifMuhammad** [comment]
> @AatifMuhammad Did you try to use Urduhack on google colab?

I just tried google colab.
The code I tried to execute is:
![coding](https://user-images.githubusercontent.com/39222895/81484265-b127a280-925d-11ea-976f-a7ebfa746a84.png)
The output I got is:
![output error](https://user-images.githubusercontent.com/39222895/81484292-dae0c980-925d-11ea-97ab-0dc27176b44e.png)
From the above image it seems like the problem is in the _word_tokenizer_.
When I tried to solve the error I got the message as given below:
![when tried to execute the command urduhack download](https://user-images.githubusercontent.com/39222895/81484315-05cb1d80-925e-11ea-9c74-8584aed7c599.png)

**Comment by akkefa** [comment]
@AatifMuhammad  you go this link.
Everything id working fine.
https://colab.research.google.com/drive/1uw_5xvXZF-qhVNYfp4O_Y6IWvrQXfLg7?usp=sharing

**Comment by akkefa** [comment]
<img width="1049" alt="Screen Shot 2020-05-10 at 1 34 04 PM" src="https://user-images.githubusercontent.com/7104938/81494520-f4682c80-92c2-11ea-90c7-517533e079a0.png">

**Comment by akkefa** [comment]
@AatifMuhammad  try to run download command with ! sign.

> !urduhack download

**Comment by AatifMuhammad** [comment]
> @AatifMuhammad try to run download command with ! sign.
> 
> > !urduhack download

Great!!!. It worked when I tried it for the 2nd time. For the first time when I tried to execute the command with ! symbol the following error message popped. 
![command not found](https://user-images.githubusercontent.com/39222895/81508760-8b62d200-931f-11ea-8d49-c298eebd33cc.png)

Then I executed the command _!pip install urduhack_ followed by _!urduhack download_. This time I am happy that it worked. :) Thank You Author @akkefa .
![working](https://user-images.githubusercontent.com/39222895/81508844-15ab3600-9320-11ea-82d3-89e805261677.png)

**Comment by AatifMuhammad** [comment]
My next tasks in my research problems are:

- compare each word of the sentence to the words saved in a list.
- if match occurs then, fetch the last word of the sentence. Add a symbol e.g. $ to this fetched word. And finally write the fetched word (along with the symbol) to its original location i.e. end of current sentence.
For example:
عراق اور شام نے اعلان کیا ہے
will become
$عراق اور شام نے اعلان کیا ہے

ANY HELP IN THIS REGARD WOULD BE HIGHLY APPRECIATED. I think the functionally of _editing an urdu document/text_ and _matching words/sentences for similarity_ does not exist in urduhack.

**Comment by muhammadfahid51** [comment]
@AatifMuhammad as of now, we haven't added any reference check function. I didn't understand your question completely but the following code will reproduce the above result. 
`reference_words = []
text = "عراق اور شام نے اعلان کیا ہے"
tokens = work_tokenize(text)
for word in tokens:
if word in reference_words:
    ' '.join(tokens) + '$'
`

**Comment by AatifMuhammad** [comment]
> @AatifMuhammad as of now, we haven't added any reference check function. I didn't understand your question completely but the following code will reproduce the above result.
> 
> ```
> reference_words = ['عراق', 'شام']
> text = "عراق اور شام نے اعلان کیا ہے"
> tokens = work_tokenize(text)
> for word in tokens:
> if word in reference_words:
>     ' '.join(tokens) + '$'
> ```

Thank You brother. :)
