### ISSUE TITLE
pip install broken

### ISSUE THREAD

**Issue by aliaanne** [urduhack/urduhack#107]
## How to reproduce the behaviour

- installing from wheel (from pypy page) is broken:
[this was tried on two different python conda environments with python 3.5.5 and 3.6 separately, with and without tensorflow installed]
$ pip install urduhack-0.3.1-py3-none-any.whl 
Processing ./urduhack-0.3.1-py3-none-any.whl
ERROR: Package 'urduhack' requires a different Python: 3.5.5 not in '>= 3.6

- installing from pip directly gives the same issue:
[this was tried on two different python conda environments with python 3.5.5 and 3.6 separately, with and without tensorflow installed]
$ pip install urduhack
ERROR: Could not find a version that satisfies the requirement urduhack (from versions: none)
ERROR: No matching distribution found for urduhack

- git cloning this directory and then installing from inside repo also fails
[this was tried on two different python conda environments with python 3.5.5 and 3.6 separately, with and without tensorflow installed]
$ pip install -e .
Obtaining ~/urduhack
ERROR: Package 'urduhack' requires a different Python: 3.5.5 not in '>= 3.6'

## Your Environment
* Operating System: ubuntu 18.04
* Python Version Used: tried both 3.5.5 and 3.6
* Urduhack Version Used:0.3.1
* Environment Information: conda

**Comment by akkefa** [comment]
@aliaanne Currently Urduhack support python 3.6 and 3.7 version.

Read the documentation.
https://urduhack.readthedocs.io/en/stable/installation.html#installation

I am working on it add support to download from conda package manager.

**Comment by akkefa** [comment]
Try this command on conda.

`conda install --from pypi urduhack`
