### ISSUE TITLE
Tokenization issues.

### ISSUE THREAD

**Issue by mirfan899** [urduhack/urduhack#108]
## How to reproduce the behavior
* Why do we have to download tokenization model and then use it to tokenize sentences?
* Punctuations are not being tokenized properly.

In NLP domain punctuations when tokenized are considered as words for example

```python
nlp = spacy.blank("en")
sentence = nlp("This is a sentence with some ?!, punctuations." )
for word in sentence:
    print(word)

This
is
a
sentence
with
some
?
!
,
punctuations
.
```
```python
import nltk
sentence = """This is a sentence with some ?!, punctuations."""
tokens = nltk.word_tokenize(sentence)
print(tokens)
['This', 'is', 'a', 'sentence', 'with', 'some', '?', '!', ',', 'punctuations', '.']
```

Urduhack does not handle punctuations.
```python
from urduhack.tokenization import sentence_tokenizer, word_tokenizer
text = """عراق اور شام نے اعلان کیا ہےدونوں ممالک جلد اپنے اپنے سفیروں کو واپس 'بغداد' اور دمشق بھیج، دیں گے’۔!؟"""
words = word_tokenizer(text)
print(words)
['عراق', 'اور', 'شام', 'نے', 'اعلان', 'کیا', 'ہے', 'دونوں', 'ممالک', 'جلد', 'اپنے', 'اپنے', 'سفیروں', 'کو', 'واپس', 'بغداد', 'اور', 'دمشق', 'بھی', 'ج،', 'دیں', 'گے۔!؟']
```

Some words are split like `بھیج` to two words `ج،`,  and `بھی`

`گے` is combined with punctuations.

## Your Environment
* Operating System: macOS
* Python Version Used: 3.7
* Urduhack Version Used: latest
* Environment Information:

**Comment by akkefa** [comment]
@mirfan899 I am working on it.

**Comment by akkefa** [comment]
@mirfan899 We will release a new model to patch these bugs.

**Comment by akkefa** [comment]
Issue fixed with the new model released.
