### ISSUE TITLE
Preprocessing module for replacing values with tag

### ISSUE THREAD

**Issue by mirfan899** [urduhack/urduhack#110]
## Feature description
I've gone through the preprocessing module, and I'm confused, why there are different features of replacing values with a token `*TAG*`.

for example, replacing URL with `*URL*`.
```python
from urduhack.preprocess import replace_urls
text = "20 www.gmail.com  فیصد"
replace_urls(text)
'20 *URL*  فیصد'
```
There are multiple functions with the functionality of replacing the text with `*TAG*`.
* replace_urls
* replace_emails
* replace_numbers
* replace_phone_numbers
* replace_currency_symbols

**Comment by akkefa** [comment]
@mirfan899 Reason we add the tag option when we are training the embeddings so that tag can represent a single vector.

**Comment by mirfan899** [comment]
How?

**Comment by akkefa** [comment]
ok. I will modify this function argument.

`def replace_urls(text: str, replace_with=''):
    """
    Replace all URLs in ``text`` str with ``replace_with`` str.

    Args:
        text (str): raw ``urdu`` text
        replace_with (str): replace string
    Returns:
        str: returns a ``str`` object replace url with ``replace_with`` text.
    """
    return _URL_RE.sub(replace_with, _SHORT_URL_RE.sub(replace_with, text))`
