### ISSUE TITLE
Image dataset?

### ISSUE THREAD

**Issue by mirfan899** [urduhack/urduhack#115]
I've gone through the `datasets` module and it needs cleaning due to the following reasons:

* Are you planning on making it a general library (ML) for Urdu instead of NLP?
* What is the purpose of the image dataset?
* No documentation?

**Comment by akkefa** [comment]
@mirfan899 we need to do meeting on this topic. Mention when you're available for google meet call?

**Comment by mirfan899** [comment]
I will be available tomorrow 1:00 pm
