### ISSUE TITLE
'Charmap' codec can't decode byte 0x81 in position 21: character maps to <undefined>

### ISSUE THREAD

**Issue by AatifMuhammad** [urduhack/urduhack#118]
Below are two images explaining the error. It is requested very humbly to help me in this regard. 

IMAGE 1:

![error-pic1](https://user-images.githubusercontent.com/39222895/83714117-4e9aaa00-a643-11ea-861a-3ef4998a2b0b.png)

IMAGE 2:

![error-pic2](https://user-images.githubusercontent.com/39222895/83714147-66722e00-a643-11ea-80dc-51f146ba56a0.png)

## Your Environment
* Operating System: Windows 10 Education (64-bit)
* Python Version Used: 3.6
* Urduhack Version Used: 0.2.7
* Environment Information: Jupyter IDE on HP Laptop intel(R) Core(TM) i5-3230M CPU @ 2.60GHz 2.60 GHz with 4 GB RAM.

**Comment by muhammadfahid51** [comment]
@AatifMuhammad need more info on this. It seems like an encoding issue. can you share about the "norm_text" and post the full error in comment.

**Comment by AatifMuhammad** [comment]
FULL CODING BELOW:
`!pip install urduhack`
`!urduhack download`
`from urduhack import normalize`
`from urduhack.normalization import normalize_characters`
`from urduhack.normalization import normalize_combine_characters`
`from urduhack.normalization import digits_space`
`from urduhack.normalization import punctuations_space`
`from urduhack.normalization import remove_diacritics`
`from urduhack.normalization import english_characters_space`

`text = " فوج کے شعبہ تعلقات عامہ (آئی ایس پی آر) گاؤں کے 6شہری زخمی ہوئےPak     ۔آئی ایس پی آر کے مطابق زخمیوں میں3بچیاں اور ایک خاتون بھی شامل ہیں،زخمیوں کواسپتالوں میں منتقل کردیا گیا ہے۔"`

`norm_text = normalize(text)`
`print(norm_text)`
`norm_text = normalize_combine_characters(norm_text)`
`print(norm_text)`
`norm_text = digits_space(norm_text)`
`print(norm_text)`
`#norm_text = punctuations_space(norm_text)`
`#print(norm_text)`
`norm_text = english_characters_space(norm_text)`
`print(norm_text)`

`# TOKENIZATION`
`import codecs`
`from urduhack.tokenization import sentence_tokenizer`
`from urduhack.tokenization import word_tokenizer`

`sentences = sentence_tokenizer(norm_text)`
`for i in range(len(sentences)):`
 `   print(sentences[i])`

THE FULL ERROR IS GIVEN ABOVE IN IMAGE 1 & IMAGE 2. THE ERROR STARTS FROM THE LINE _UnicodeDecodeError                        Traceback (most recent call last)_ AND ENDS AT _UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 21: character maps to undefined_

I AM WORKING ON A RESEARCH PROBLEM WHILE USING URDUHACK. ANY HELP IN THIS REGARD IS HIGHLY APPRECIATED.

**Comment by muhammadfahid51** [comment]
I ran the code locally as well as in Colab and it ran without error. This issue is an encoding issue, you have to mention that text encoding type.
[Colab Solved](https://colab.research.google.com/drive/1_gg2SG4djmQIrHfteCMDz3Dz8yj3Bwif?usp=sharing)

**Comment by AatifMuhammad** [comment]
Dear @muhammadfahid51 thank You for the time & help. The code is working fine at Colab as you said. Therefore, I will try to do things online at Colab to avoid further issues. However, I could not understand what do you mean by _mention that text encoding_ & _how to mention._ Anyhow, Thank You once again.

**Comment by AatifMuhammad** [comment]
I will close the issue. Till that, your valuable guidlines/suggestions are appreciated.
