### ISSUE TITLE
ValueError: Layer #3 (named "crf_2" in the current model) was found to correspond to layer crf in the save file. However the new layer crf_2 expects 5 weights, but the saved weights have 1 elements.

### ISSUE THREAD

**Issue by Khubaibahmed-dev** [urduhack/urduhack#138]
ValueError: Layer #3 (named "crf_2" in the current model) was found to correspond to layer crf in the save file. However the new layer crf_2 expects 5 weights, but the saved weights have 1 elements.

**Comment by Khubaibahmed-dev** [comment]
>>> from urduhack import Pipeline
>>> nlp = Pipeline()
>>> text = """
گزشتہ ایک روز کے دوران کورونا کے سبب 118 اموات ہوئیں جس کے بعد اموات کا مجموعہ 3 ہزار 93 ہوگیا ہے۔
سب سے زیادہ اموات بھی پنجاب میں ہوئی ہیں جہاں ایک ہزار 202 افراد جان کی بازی ہار چکے ہیں۔
سندھ میں 916، خیبر پختونخوا میں 755، اسلام آباد میں 94، گلگت بلتستان میں 18، بلوچستان میں 93 اور ا?زاد کشمیر میں 15 افراد کورونا وائرس سے جاں بحق ہو چکے ہیں۔
"""
>>> doc = nlp(text)
>>> print(doc.text)

**Comment by bm2515** [comment]
I'm getting the same error with this piece of code:

import urduhack
urduhack.download()
nlp = urduhack.Pipeline()
text = "الیکشن تو سلیکشن تھا ایسا ہی ہونا تھا سوہو گیا ۔ اندازہ تھا ، اس لئے کوئی حیرت کی بات نہیں ۔"
doc = nlp(text)

**Comment by bm2515** [comment]
> ValueError: Layer #3 (named "crf_1" in the current model) was found to correspond to layer crf in the save file. However the new layer crf_1 expects 5 weights, but the saved weights have 1 elements.

**Comment by bm2515** [comment]
@akkefa @fahdrazavi can we please get any update on the timeline for resolving the error? I am using this library to work on my senior year capstone project at NYU and would like to know if I should expect more errors moving forward

**Comment by muhammadfahid51** [comment]
@bm2515 @Khubaibahmed-dev this error is being raised because of some compatibility issues in external dependencies. 

Will be resolved soon.

**Comment by muhammadfahid51** [comment]
@bm2515 @Khubaibahmed-dev  after installing urduhack and tensorflow install tf2crf 0.1.13 using the following install command.

`
pip install tf2crf==0.1.13
`

It will resolve run the code successfully. 

This bug will be removed in the next release.

**Comment by Khubaibahmed-dev** [comment]
Thanks man, worked, Really appreciated.

Can you give me example  code for stop words removal  use this urduhack library.
