### ISSUE TITLE
Environment for Urdu NLP

### ISSUE THREAD

**Issue by Akhtar303** [urduhack/urduhack#22]
Hi @akkefa and  @muzzammilh , I want to work on Urdu NLP in python3 with Ubuntu 18.04 so please suggest me any Programming ide /editor to work on it easily .
currently I am using atom and ML-term but I am facing some issues , so please suggest me any ide  for long term solution for Urdu Language.

Thanks

**Comment by akkefa** [comment]
@Akhtar303 Use pycharm.

**Comment by akkefa** [comment]
@Akhtar303 Can you help us for data related task.

Can you improve these words list we need for preparing the datasets? 

**Words list**
https://github.com/urduhack/urdu-words/blob/master/words.txt
