### ISSUE TITLE
Issue in sentence tokenization

### ISSUE THREAD

**Issue by naeem9** [urduhack/urduhack#43]
Following is the text containing 4 sentences.
اب درست رائے تو وہی دے سکتے ہیں جنہیں اس رویے سے پالا پڑتا ہے۔ یہ وہ معاشرے ہیں جو فطری انداز میں ارتقائی مراحل سے گزرتے ہیں۔ مادی مطالبات وہ ہیں جن کا تعلق جسم سے ہے۔ جمالیاتی حس بھی فطری ہے جس کی بنیاد پر وہ کسی چیز کے خوش شکل، خوش رنگ، خوش گلو یا دیدہ زیب ہونے کا فیصلہ کرتا ہے۔ انسانی وجود کا نفسیاتی پہلو وہ ہے جو اسے کسی سے قریب اور کسی سے دور کرتا ہے۔
When this text is given to **sentence_tokenizer** it returns 10 sentences instead of 4.

`from urduhack.tokenization import sentence_tokenizer
text='اب درست رائے تو وہی دے سکتے ہیں جنہیں اس رویے سے پالا پڑتا ہے۔ یہ وہ معاشرے ہیں جو فطری انداز میں ارتقائی مراحل سے گزرتے ہیں۔ مادی مطالبات وہ ہیں جن کا تعلق جسم سے ہے۔ جمالیاتی حس بھی فطری ہے جس کی بنیاد پر وہ کسی چیز کے خوش شکل، خوش رنگ، خوش گلو یا دیدہ زیب ہونے کا فیصلہ کرتا ہے۔ انسانی وجود کا نفسیاتی پہلو وہ ہے جو اسے کسی سے قریب اور کسی سے دور کرتا ہے۔'
sentences = sentence_tokenizer(text)
print('no of sentences')
print(len(sentences))
print(sentences)
`
It is breaking the sentence where it find a pair of words
ہیں جنہیں
ہیں جو
ہیں جن
ہے جس
ہے جو

**Comment by truefriend2004** [comment]
The standard practice in English (and other languages) is to split sentences based on punctuation, and not on clause grammar, conjunctions or anything that marks the end of a clause. The same should be implemented for Urdu as well.

**Comment by naeem9** [comment]
Solution of this issue is
add  these words ('جنہیں','جس','جن','جو') in URDU_CONJUNCTIONS
urduhack/urduhack/tokenization/eos.py
at line # 6
