### ISSUE TITLE
Request: normalization of quotes

### ISSUE THREAD

**Issue by urdutext** [urduhack/urduhack#44]
It is noted that Urdu text contains multiple types of quotes in it.
consider following sentence:
اردو میں ”واوین“ کی ’یونیکوڈ‘ قدریں کیا "انگریزی ڈبل کوٹس" سے 'مختلف'  ہیں
![quotes](https://user-images.githubusercontent.com/58520117/70171318-4f806c80-16f0-11ea-9166-cceb1ec32bd6.PNG)
It contains 4 types of quotes.
It is suggested that all quotes are normalized to one type for the sake of uniformity.

**Comment by akkefa** [comment]
@naeem9 I will look into this issue.

**Comment by naeem9** [comment]
@akkefa 
thanks!

**Comment by naeem9** [comment]
Which quote should be considered as a standard while normalization of quotes?

**Comment by naeem9** [comment]
following code normalize all quotes to double quote

```
QUOTE_TRANSLATION_TABLE = {
    ord(x) : ord(y)
    for x, y in zip("'ʼ‘’´`“”", "\"\"\"\"\"\"\"\"")
    }
text='اردو میں ”واوین“ کی ’یونیکوڈ‘ قدریں کیا "انگریزی ڈبل کوٹس" سے \'مختلف\' ہیں'
print(text.translate(QUOTE_TRANSLATION_TABLE) )
```

**Comment by akkefa** [comment]
@naeem9 I will add the fix soon.
