### ISSUE TITLE
Error in Characters Normalization code sample

### ISSUE THREAD

**Issue by naeem9** [urduhack/urduhack#47]
In
urduhack/docs/handbook/tutorial/normalization.rst
under Characters Normalization a code sample is given in which Text and normalized_text both have same unicode values. There is no change in text and normalized_text

text:مجھ کو جو توڑا گیا تھا
unicode:
%u0645%u062C%u06BE%20%u06A9%u0648%20%u062C%u0648%20%u062A%u0648%u0691%u0627%20%u06AF%u06CC%u0627%20%u062A%u06BE%u0627

normalized_text:
مجھ کو جو توڑا گیا تھا
unicode:
%u0645%u062C%u06BE%20%u06A9%u0648%20%u062C%u0648%20%u062A%u0648%u0691%u0627%20%u06AF%u06CC%u0627%20%u062A%u06BE%u0627

for text to Unicode:
https://www.online-toolz.com/tools/text-unicode-entities-convertor.php
for diff:
https://www.diffchecker.com/diff

**Comment by muhammadfahid51** [comment]
There is no issue in the above text because the text before normalization and after it has the same characters. 
Now if you try to normalize this:
text = "مجھ کو جو توڑا ﮔیا تھا"
It will give you the result:
normalized_text = "مجھ کو جو توڑا گیا تھا"
and there encodings will be different as well.
