### ISSUE TITLE
Normalization: Removal of tatweel/kashida character

### ISSUE THREAD

**Issue by naeem9** [urduhack/urduhack#50]
Tatweel character is used to stretch some character present in the word. 
It should be removed from text during normalization.

Tatweel character: ـ
unicode value: 0640

![tatweel](https://user-images.githubusercontent.com/58520117/70319901-40f79980-1845-11ea-984e-bed71f80c9ec.PNG)

sample code:
from urduhack.normalization import normalize
text = "کــــــاتب  حضــرات"
normalized_text = normalize(text)
#Normalized text 
print(normalized_text)
desired output:
کاتب حضرات

**Comment by akkefa** [comment]
@naeem9 Sure. We will fix this issue with next release.
