### ISSUE TITLE
Normalization: Replace ِArabic ة with Urdu ۃ

### ISSUE THREAD

**Issue by naeem9** [urduhack/urduhack#51]
It is requested that  ِArabic ة should be replaced with Urdu ۃ during normalization
![چھوٹی ت](https://user-images.githubusercontent.com/58520117/70325504-f3cef400-1853-11ea-810d-b4c50d729b38.PNG)

**Comment by akkefa** [comment]
@naeem9  With the new release this bug will be fixed.

**Comment by naeem9** [comment]
> @naeem9 With the new release this bug will be fixed.

thanks!
