### ISSUE TITLE
question: how to replace multiple ۔۔۔ with one ۔

### ISSUE THREAD

**Issue by naeem9** [urduhack/urduhack#52]
dear all
i am processing a text which contain multiple end of sentence mark like
text=" اس کو تو یاد ہی نہیں رہا۔۔۔۔۔۔۔۔"
how to get desired text using any urduhack function
desired text="اس کو تو یاد ہی نہیں رہا۔"
Thanks!
currently i am using following code
```
from urduhack.normalization import normalize
text="اس کو تو یاد ہی نہیں رہا۔۔۔۔۔۔۔۔" 
normalized_text = normalize(text)
print(normalized_text)

```
output is:
اس کو تو یاد ہی نہیں رہا۔۔۔۔۔۔۔۔
desired output:
اس کو تو یاد ہی نہیں رہا۔

**Comment by naeem9** [comment]
ایک خراب حال متن جس میں عربی  ، اعراب ، وائٹ سپیسز ، تطویل اور متعدد ختمہ کے نشان موجود ہیں
text=
" ﻭﻩ ﺟﻨﮕﻞ ﺑﯿﺎﺑﺎﻥ ﻣﯿﮟ ﺍﭘﻨﯽ ﺳﻮﺍﺭﯼ ﭘﺮ ﺳﻔﺮ ﮐﺮ ﺭﮨﺎ ﺗﮭﺎ ﺍﺱ ﭘﺮ ﺍﺱ ﮐﺎ ﮐﮭﺎﻧﺎ ﭘﯿﻨﺎ ﺑﮭﯽ ﺗﮭﺎ ۔۔۔۔ اِن شَاء اللہ آنـــا جَانـــا   لَـــگا        رہے گا\n\n\t"

from urduhack.normalization import normalize
from urduhack.preprocess import normalize_whitespace
from urduhack.tokenization import sentence_tokenizer

text=text=" ﻭﻩ ﺟﻨﮕﻞ ﺑﯿﺎﺑﺎﻥ ﻣﯿﮟ ﺍﭘﻨﯽ ﺳﻮﺍﺭﯼ ﭘﺮ ﺳﻔﺮ ﮐﺮ ﺭﮨﺎ ﺗﮭﺎ ﺍﺱ ﭘﺮ ﺍﺱ ﮐﺎ ﮐﮭﺎﻧﺎ ﭘﯿﻨﺎ ﺑﮭﯽ ﺗﮭﺎ ۔۔۔۔ اِن شَاء اللہ آنـــا جَانـــا   لَـــگا        رہے گا\n\n\t"
# normalize function does not removes whitespace from text , so explicitly call to normalize_whitespace after normaliz
normalized_text = normalize_whitespace(normalize(text))
# remove tatweel from text
translation_table = dict.fromkeys(map(ord, 'ـ'), None)
normalized_text = normalized_text.translate(translation_table)
print('normalized text is:')
print(normalized_text)
# after sentencet tokenization multiple "۔۔۔۔" are eliminated
sentences=sentence_tokenizer(normalized_text)
print(sentences)
output:
وہ جنگل بیابان میں اپنی سواری پر سفر کر رہا تھا اس پر اس کا کھانا پینا بھی تھا۔۔۔۔ ان شاء اللہ آنـــا جانـــا لـــگا رہے گا
['وہ جنگل بیابان میں اپنی سواری پر سفر کر رہا تھا۔', 'اس پر اس کا کھانا پینا بھی تھا۔', 'ان شاء اللہ آنا جانا لگا رہے گا']
>>> 
Excellent result!
thanks urduhack for great work.

**Comment by akkefa** [comment]
@naeem9  Replacing multiple ۔۔۔  with one you can use regex for this task. We only add those helper functions which will help us to clean Urdu data.

I hope this will fulfil your concern.

**Comment by akkefa** [comment]
> ایک خراب حال متن جس میں عربی ، اعراب ، وائٹ سپیسز ، تطویل اور متعدد ختمہ کے نشان موجود ہیں
> text=
> " ﻭﻩ ﺟﻨﮕﻞ ﺑﯿﺎﺑﺎﻥ ﻣﯿﮟ ﺍﭘﻨﯽ ﺳﻮﺍﺭﯼ ﭘﺮ ﺳﻔﺮ ﮐﺮ ﺭﮨﺎ ﺗﮭﺎ ﺍﺱ ﭘﺮ ﺍﺱ ﮐﺎ ﮐﮭﺎﻧﺎ ﭘﯿﻨﺎ ﺑﮭﯽ ﺗﮭﺎ ۔۔۔۔ اِن شَاء اللہ آنـــا جَانـــا لَـــگا رہے گا\n\n\t"
> 
> ```
> from urduhack.normalization import normalize
> from urduhack.preprocess import normalize_whitespace
> from urduhack.tokenization import sentence_tokenizer
> 
> text=" ﻭﻩ ﺟﻨﮕﻞ ﺑﯿﺎﺑﺎﻥ ﻣﯿﮟ ﺍﭘﻨﯽ ﺳﻮﺍﺭﯼ ﭘﺮ ﺳﻔﺮ ﮐﺮ ﺭﮨﺎ ﺗﮭﺎ ﺍﺱ ﭘﺮ ﺍﺱ ﮐﺎ ﮐﮭﺎﻧﺎ ﭘﯿﻨﺎ ﺑﮭﯽ ﺗﮭﺎ ۔۔۔۔ اِن شَاء اللہ آنـــا جَانـــا   لَـــگا        رہے گا\n\n\t"
> #normalize function does not removes whitespace from text , so explicitly call to normalize_whitespace after normaliz
> normalized_text = normalize_whitespace(normalize(text))
> #remove tatweel from text
> translation_table = dict.fromkeys(map(ord, 'ـ'), None)
> normalized_text = normalized_text.translate(translation_table)
> print('normalized text is:')
> print(normalized_text)
> #after sentence tokenization multiple "۔۔۔۔" are eliminated
> sentences=sentence_tokenizer(normalized_text)
> print(sentences)
> ```
> 
> output:
> وہ جنگل بیابان میں اپنی سواری پر سفر کر رہا تھا اس پر اس کا کھانا پینا بھی تھا۔۔۔۔ ان شاء اللہ آنـــا جانـــا لـــگا رہے گا
> ['وہ جنگل بیابان میں اپنی سواری پر سفر کر رہا تھا۔', 'اس پر اس کا کھانا پینا بھی تھا۔', 'ان شاء اللہ آنا جانا لگا رہے گا']
> 
> > > >
> 
> ![output](https://user-images.githubusercontent.com/58520117/70362972-86997e00-18a8-11ea-8c30-28352307c61d.PNG)
> 
> Excellent result!
> thanks urduhack team for great work.

Yes. **normalize** function will only clean the Urdu data for valid format.
