### ISSUE TITLE
Documentation: Conversion of Unicode value of initial , medial and final form of character with isolated form 

### ISSUE THREAD

**Issue by naeem9** [urduhack/urduhack#58]
Although it is doing conversion very well. the following text may be added somewhere in documentation for the sake of user clarity.

اردو یا عربی میں ایک ہی حرف کی مختلف اشکال ہوتی ہیں۔
'ﻑ', ' ﻒ ', ' ﻓ ', ' ﻔ 

اکیلی شکل Isolated form
ابتدائی شکل Initial form
وسطی شکل Medial form
آخری شکل Final form
یونیکوڈ میں حرف کی اکیلی شکل ، ابتدائی شکل ، وسطی شکل اور آخری شکل کی علیحدہ علیحدہ یونیکوڈ ویلیوز ہیں۔

کی بورڈ سے لکھتے ہوئے عموما حرف کی اکیلی شکل ہی لکھی جاتی ہے اور لے آوٹ انجن فونٹ سے حرف کے کانٹیکسٹ کے مطابق مطلوبہ شکل مہیا کرتا ہے
اشکال کو تبدیل کرنے کا یہ عمل
reshaping engine
کی ذمہ داری ہوتی ہے۔

جن سسٹمز میں رائٹ ٹو لیفٹ زبان کی لے آوٹ اور ری شیپنگ کی صلاحیت نہیں ہوتی وہاں ایک جگاڑ یہ بنا لیا جاتا ہے کہ حرف کی اکیلی شکل کے بجائے 
context
کے مطابق حروف کی یونیکوڈ ویلیو لے آوٹ انجن کو فراہم کی جاتی ہیں اور اس طرح درست ڈسپلے ممکن ہوتا ہے۔
لیکن سرچ کرتے ہوئے اس طرح کے متن کی تلاش مشکل ہوتی ہے۔ 
لہذا نارملائزیشن کے عمل میں یہ ضروری ہوتا ہے کہ حرف کی ابتدائی ، وسطی اور آخری شکل کو آسولیٹیڈ فارم سے تبدیل کر دیا جائے۔
![aaa](https://user-images.githubusercontent.com/58520117/70933861-847caf80-205e-11ea-8c9c-5755dc88bf9e.png)

**Comment by akkefa** [comment]
@naeem9 Thanks. I will add this in Urdu character repo.(https://github.com/urduhack/urdu-characters)

**Comment by akkefa** [comment]
@naeem9  added in this repo. https://github.com/urduhack/urdu-characters

**Comment by naeem9** [comment]
thanks!
