### ISSUE TITLE
Request: IsNormalized()

### ISSUE THREAD

**Issue by naeem9** [urduhack/urduhack#60]
Dear Developers!
It is requested that **IsNormalized**(text) function should be added which takes text as input and return true if it is normalized text and false otherwise.
Thanks

**Comment by akkefa** [comment]
@naeem9 why not we use always normalize() function on top of every script.

**Comment by naeem9** [comment]
> 
> 
> @naeem9 why not we use always normalize() function on top of every script.

that is very appropriate. thanks
