### ISSUE TITLE
Download all datasets from s3.

### ISSUE THREAD

**Issue by akkefa** [urduhack/urduhack#61]
Download all datasets from s3 storage.

**Comment by muhammadfahid51** [comment]
Please add links to the s3 storage files.

**Comment by akkefa** [comment]
### All datasets link  @muhammadfahid51 

**Urdu point datasets**
https://dataset.sgp1.digitaloceanspaces.com/urdupoint/6000-836520_urdupoint_771624_posts-raw.pkl?AWSAccessKeyId=7BI2LGG6HJZOYEWKVZWR&Expires=1580899592&Signature=oifyeoWPyX3TCD5kWV3gqBL99yQ%3D

https://dataset.sgp1.digitaloceanspaces.com/urdupoint/836520-1480025_urdupoint_599376_posts-raw.pkl?AWSAccessKeyId=7BI2LGG6HJZOYEWKVZWR&Expires=1580899623&Signature=kWfA0%2BfbIgKl2ErRv98IN%2FHKAQw%3D

https://dataset.sgp1.digitaloceanspaces.com/urdupoint/1480025-1817939_urdupoint_312688_posts-raw.pkl?AWSAccessKeyId=7BI2LGG6HJZOYEWKVZWR&Expires=1580899633&Signature=HAkruOtGUQdiindyK2OUK5TP7ME%3D

**Ary news**

https://dataset.sgp1.digitaloceanspaces.com/arynews/arynews_86686_posts-raw.pkl?AWSAccessKeyId=7BI2LGG6HJZOYEWKVZWR&Expires=1580899673&Signature=UgzvktBStCL4rtLJ3naTe7Cd%2Bz0%3D

**Bathak**

https://dataset.sgp1.digitaloceanspaces.com/bathak/125-192971_bathak_57219_posts-raw.pkl?AWSAccessKeyId=7BI2LGG6HJZOYEWKVZWR&Expires=1580899693&Signature=I87uknZgo11INwxDFH4MjWqaZNI%3D

**Wikipedia**

https://dataset.sgp1.digitaloceanspaces.com/wiki/wiki_83840_posts-raw.pkl?AWSAccessKeyId=7BI2LGG6HJZOYEWKVZWR&Expires=1580899723&Signature=S9GucEJY7%2FZgHnPoRThM94z4XTg%3D

https://dataset.sgp1.digitaloceanspaces.com/wiki/wiki_84645_posts-08-Apr-2019-raw.pkl?AWSAccessKeyId=7BI2LGG6HJZOYEWKVZWR&Expires=1580899735&Signature=Mh3Zjza4ZN5UPKzP3CzfHEdaoWI%3D

**Comment by muhammadfahid51** [comment]
All files are downloaded.
