### ISSUE TITLE
Generate one file to store all Urdu tokenize data.

### ISSUE THREAD

**Issue by akkefa** [urduhack/urduhack#62]
### Steps to follow

- [x]  Loop through all datasets.
- [x]  Normalize it
- [x]  Generate sentences from blogs
- [x]  Generate word tokens from sentences 
- [x]  Save into the one format. (pkl, h5 or do RnD)
- [x] Filename suggestion

**Comment by naeem9** [comment]
Excellent!
you can use/contribute [urdu sentences](https://github.com/naeem9/urdu-sentences)
