### ISSUE TITLE
support for extraction of comma separated sentences from text

### ISSUE THREAD

**Issue by urdutext** [urduhack/urduhack#66]
مندرجہ ذیل جملے کو دیکھیے:

چند دن پہلے ایک دوست سے ملاقات ہوئی، وہ رنجیدہ دکھائی دئیے، معلوم ہوا کہ ان کے ایک محلے دار کا نوجوان لڑکا انتقال کر گیا ہے، وہ کینسر کا مریض تھا۔
source of text
http://www.inzaar.pk/hum-kahan-ja-rahy-hain-by-muhammad-aamir-khakwani/

اس میں سے  مندرجہ ذیل جملے نکالے جا سکتے ہیں؟ جب کہ اردو ھیک اس کو ایک جملہ دکھا رہا ہے

    چند دن پہلے ایک دوست سے ملاقات ہوئی
    وہ رنجیدہ دکھائی دئیے
    معلوم ہوا کہ ان کے ایک محلے دار کا نوجوان لڑکا انتقال کر گیا ہے
    وہ کینسر کا مریض تھا

`from urduhack.normalization import normalize
from urduhack.preprocess import normalize_whitespace
from urduhack.tokenization import *

text='چند دن پہلے ایک دوست سے ملاقات ہوئی، وہ رنجیدہ دکھائی دئیے، معلوم ہوا کہ ان کے ایک محلے دار کا نوجوان لڑکا انتقال کر گیا ہے، وہ کینسر کا مریض تھا۔'
normalized_text = normalize_whitespace(normalize(text))
sentences=sentence_tokenizer(normalized_text)
print(sentences)
`

**Comment by talhaanwarch** [comment]
here is the quick solution:
text='چند دن پہلے ایک دوست سے ملاقات ہوئی، وہ رنجیدہ دکھائی دئیے، معلوم ہوا کہ ان کے ایک محلے دار کا نوجوان لڑکا انتقال کر گیا ہے، وہ کینسر کا مریض تھا۔'

`text.split("،")`

Output:
['چند دن پہلے ایک دوست سے ملاقات ہوئی',
 ' وہ رنجیدہ دکھائی دئیے',
 ' معلوم ہوا کہ ان کے ایک محلے دار کا نوجوان لڑکا انتقال کر گیا ہے',
 ' وہ کینسر کا مریض تھا۔']
