### ISSUE TITLE
Pytest failing on windows OS.

### ISSUE THREAD

**Issue by akkefa** [urduhack/urduhack#99]
## How to reproduce the behaviour

**Link to follow**
`pytest --cov=./ --ignore=urduhack/tasks`
https://travis-ci.org/github/urduhack/urduhack/jobs/682254220

## Your Environment
* Operating System:
* Python Version Used:
* Urduhack Version Used:
* Environment Information:

**Comment by AatifMuhammad** [comment]
Dear all,
I am waiting eagerly for the solution of issue #99. Hoping it be solved soon, God Willingly.
Thank you
